spring:
  datasource:
    password: '{SM4}9a9ab954111a3342f03042b195527d48'
    driverClassName: com.mysql.cj.jdbc.Driver
    url: '{SM4}75d5fa7c21f98c835bff5803d4fb55dfc2d3d9c3b277de34fa33a1188cbc6d882bf14e1b1ebe51a2a2d7f39f15fb31d6'
    username: '{SM4}9a9ab954111a3342f03042b195527d48'
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/usercenter/*Mapper.xml
#  type-aliases-super-type: com.harbor.usercenter.entity
logging:
  level:
    org:
      springframework: info
